### ISSUE TITLE
 Special UUIDv7 function uuidv7_sub_ms() for microservices

### ISSUE THREAD

**Issue by sergeyprokhorenko** [dverite/postgres-uuidv7-sql#1]
The entire timestamp should acts as a counter in rare case when more than about 4 identifiers per microsecond are generated.

It would be great to add the ability to offset the timestamp by a specified [interval](https://postgrespro.com/docs/postgresql/16/datatype-datetime#DATATYPE-INTERVAL-INPUT) to hide the record creation time for information security. If offset would cause the timestamp to be outside the allowed range, it should not be applied.

See the C implementation [v27-0001-Implement-UUID-v7.patch](https://www.postgresql.org/message-id/attachment/163415/v27-0001-Implement-UUID-v7.patch) of Method 3 for PostgreSQL at [the page](https://commitfest.postgresql.org/47/4388/) as a reference.

**Comment by dverite** [comment]
I'm quite unconvinced about fuzzing the creation time. In particular, it breaks locality and ordering which are the main points of UUIDv7. My opinion is that if you want to keep the creation time secret, then do not use UUIDv7, or do not export it. Anyway, since commit bde5fa12988e9be8e8a2dbd0fc81816c5f74cab0 adds the ability to pass a timestamp, one can now call `uuidv7(clock_timestamp() + random interval)` if desired.

For the issue of consecutive calls that occur so fast that the precision is not sufficient to guarantee monotonicity, it seems to me that a proper solution is beyond the scope of this extension with its simple SQL functions that don't store or share anything across calls.
